vse: &vse
  docker:
    - image: circleci/node:8.11.3
    
vsedep: &vsedep
  docker:
    - image: ansible/ansible:ubuntu1604

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    <<: *vsedep
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Installing dependencies
          command: |
             sudo pip install ansible boto boto3

      - run:
          name: Ansible test
          command: |
            ansible --version

#      - run:
#          name: Let´s go AWS
#          command: |
#            cd ./ansible && ansible-playbook

      - run:
          name: Ansible deploy
          command: |
            AWS_ACCESS_KEY_ID="ASIASIRJ3ZBCOF3NNGGF"
            AWS_SECRET_ACCESS_KEY="o/b+X1w4fgwBB8QCci90Ts/feEIE0zVChG5QPXHf"
            AWS_SECURITY_TOKEN="IQoJb3JpZ2luX2VjELX//////////wEaCXVzLXdlc3QtMiJHMEUCIATXR42pcLaHnCOM5avsgMcWLs+IcxMnmRQKgiNmm6h2AiEA3ZO8o86tj8gpgGpyrUY62m1UsQ7HtCc08rkDy5TEt20qsgIIThAAGgwxNTU3ODAzNjg0NTIiDEUYJ3RDoSd0V4M+WCqPAiBGpd0IuYqRIXQNO5F/I34rI0ZmURSOE3hIAaNsZm/BBw6mW/tYIYc4p/mVWAw8bFkoe146SD/08nomlR3HqL4oD5Hah38+1VBsaURn8p++6n8ekGHCKmYYbOrtTh96KAIZ+vG5+qdXW/y1FLDwgtzYYO5HDiFcUOdXBR7BtykpkBAIUWfVlOcdcUiFHrtFU1VtZCdINfAoJCDl7zuvA8LqlG1Gw377QgUWinjsEUZXm8dBlESdO7WOkb5pj2tcbWYOahYEavoRYB9BHrzDrp+xWChiEEMTJfKN33hdtEmN/cRxrv8WCwj/5s4sCPyzhH/OE7ScPW1W8eBeVnh5Q9S+MDtS+gIZz/Zgcsqn5SIw3K+LhQY6nQFHXPieCgMyx8FcbyCPgTpzLXKa22wVsSnOT3vma4szex4maMWKRJBkdHKb3FVvwvIF7eC6ghoPC5RY3QA+3zwgTjo74iZJrVVAhSESy8tSvLFQxVmeNpSZ8UDFYZe7QJ1SeHMDDICDWcTVHzTAWOTqex6WVitq+aJSkI3nsYTeQrBUprLDnnuUV9O8ha2Pj/vQ03btljn2TwHHfoR9"
            ansible-playbook ./ansible/ec2_deploy.yml --user ubuntu --ssh-common-args='-o StrictHostKeyChecking=no'


workflows:
  version: 2.1
  execute:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: main

