- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: launch EC2 instance
      ec2:
        instance_type: t2.small
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-2b596166
#        vpc_subnet_id: subnet-8576f9a4
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
      register: ec2

    - name: Join instance to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: SSH connect Timeout
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=700 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Docker setup
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes

    - service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Repo clone
      git:
        repo: 'https://github.com/mchobodides/semestralka.git'
        dest: ./app

    - name: Build Docker
      shell: cd ./app && docker build -t myeshop:latest .
      become: yes

    - name: Run Docker
      shell: docker run -p 80:3000 myeshop
      async: 120
      poll: 0
      become: yes

    - wait_for:
        port: 80
